#define NRF_SDH_ANT_TOTAL_CHANNELS_ALLOCATED 2

#define APP_PWM_ENABLED 1
#define NRFX_TIMER_ENABLED 1
#define NRFX_TIMER1_ENABLED 1
#define NRFX_TIMER2_ENABLED 1
#define NRFX_PPI_ENABLED 1

#define TWI_ENABLED 1
#define TWI0_ENABLED 1

#define NRF_PWR_MGMT_CONFIG_DEBUG_PIN_ENABLED 0
