/* Target definition */
#define TARGET_PCA10040 1
#define TARGET_SPOTLIGHT 2
#define TARGET_ACTIK 4

#define TARGET TARGET_PCA10040

/* SDK config overrides */

#define NRF_FPRINTF_FLAG_AUTOMATIC_CR_ON_LF_ENABLED 0

#if TARGET == TARGET_SPOTLIGHT
#define NRF_BL_DFU_ENTER_METHOD_BUTTON_PIN 6
#elif TARGET == TARGET_ACTIK
#define NRF_BL_DFU_ENTER_METHOD_BUTTON_PIN 14
#endif
