name: Firmware build

on:
  push:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Zephyr project
        uses: fabiobaltieri/zephyr-setup@main
        with:
          app-path: firmware

      - name: Build
        run: |
          west build firmware -DCONFIG_MCUBOOT_SIGNATURE_KEY_FILE="\"bootloader/mcuboot/root-rsa-2048.pem\""
